<?php

namespace Service\FileGenerators;

class ProjectGenerator {

    /**
     * @var string
     */
    private $seperator = DIRECTORY_SEPARATOR;

    /**
     * @var string
     */
    private $path = '';

    /**
     * @var string
     */
    private $projectGUID = '';
    /**
     * @var string
     */
    private $entryPoint = '';

    private $references = [];

    public function __construct(string $path, $modName, $projectGUID, $entryPoint)
    {

        $this->references = [
            [
                'name'=> 'TaleWorlds.BattlEye.Client',
                'file' => 'TaleWorlds.BattlEye.Client.dll',
                'path' => "{$this->seperator}bin{$this->seperator}Win64_Shipping_Client{$this->seperator}"
            ]
        ];
    }

    public function createFile() {
        /**
        $seperator = DIRECTORY_SEPARATOR;
        $path = htmlspecialchars($this->config->get()['folders']['out']);
        $mainBin = $path . $seperator . 'bin' . $seperator . 'Win64_Shipping_Client' . $seperator;
        $modulePath = $path . $seperator . 'Modules' . $seperator;



        $file = <<<EOF
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{$this->projectGUID}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>{$this->modName}</RootNamespace>
    <AssemblyName>{$this->modName}</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>{$modulePath}{$this->modName}{$seperator}bin{$seperator}Win64_Shipping_Client{$seperator}</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="TaleWorlds.BattlEye.Client">
      <HintPath>{$mainBin}TaleWorlds.BattlEye.Client.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.CampaignSystem">
      <HintPath>{$mainBin}TaleWorlds.CampaignSystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.CampaignSystem.ViewModelCollection">
      <HintPath>{$mainBin}TaleWorlds.CampaignSystem.ViewModelCollection.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Core">
      <HintPath>{$mainBin}TaleWorlds.Core.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Core.ViewModelCollection">
      <HintPath>{$mainBin}TaleWorlds.Core.ViewModelCollection.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Diamond">
      <HintPath>{$mainBin}TaleWorlds.Diamond.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Diamond.AccessProvider.Epic">
      <HintPath>{$mainBin}TaleWorlds.Diamond.AccessProvider.Epic.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Diamond.AccessProvider.Steam">
      <HintPath>{$mainBin}TaleWorlds.Diamond.AccessProvider.Steam.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Diamond.AccessProvider.Test">
      <HintPath>{$mainBin}TaleWorlds.Diamond.AccessProvider.Test.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.DotNet">
      <HintPath>{$mainBin}TaleWorlds.DotNet.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.DotNet.AutoGenerated">
      <HintPath>{$mainBin}TaleWorlds.DotNet.AutoGenerated.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Engine">
      <HintPath>{$mainBin}TaleWorlds.Engine.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Engine.AutoGenerated">
      <HintPath>{$mainBin}TaleWorlds.Engine.AutoGenerated.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Engine.GauntletUI">
      <HintPath>{$mainBin}TaleWorlds.Engine.GauntletUI.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI">
      <HintPath>{$mainBin}TaleWorlds.GauntletUI.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI.Data">
      <HintPath>{$mainBin}TaleWorlds.GauntletUI.Data.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI.ExtraWidgets">
      <HintPath>{$mainBin}TaleWorlds.GauntletUI.ExtraWidgets.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI.PrefabSystem">
      <HintPath>{$mainBin}TaleWorlds.GauntletUI.PrefabSystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI.TooltipExtensions">
      <HintPath>{$mainBin}TaleWorlds.GauntletUI.TooltipExtensions.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.InputSystem">
      <HintPath>{$mainBin}TaleWorlds.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Library">
      <HintPath>{$mainBin}TaleWorlds.Library.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Localization">
      <HintPath>{$mainBin}TaleWorlds.Localization.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>{$mainBin}TaleWorlds.MountAndBlade.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade.AutoGenerated">
      <HintPath>{$mainBin}TaleWorlds.MountAndBlade.AutoGenerated.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade.CustomBattle">
      <HintPath>{$modulePath}CustomBattle{$seperator}bin{$seperator}Win64_Shipping_Client{$seperator}TaleWorlds.MountAndBlade.CustomBattle.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade.Diamond">
      <HintPath>{$mainBin}TaleWorlds.MountAndBlade.Diamond.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade.GauntletUI">
      <HintPath>{$modulePath}Native{$seperator}bin{$seperator}Win64_Shipping_Client{$seperator}TaleWorlds.MountAndBlade.GauntletUI.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade.GauntletUI.Widgets">
      <HintPath>{$mainBin}TaleWorlds.MountAndBlade.GauntletUI.Widgets.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade.Helpers">
      <HintPath>{$mainBin}TaleWorlds.MountAndBlade.Helpers.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade.View">
      <HintPath>{$modulePath}Native{$seperator}bin{$seperator}Win64_Shipping_Client{$seperator}TaleWorlds.MountAndBlade.View.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade.ViewModelCollection">
      <HintPath>{$mainBin}TaleWorlds.MountAndBlade.ViewModelCollection.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.NavigationSystem">
      <HintPath>{$mainBin}TaleWorlds.NavigationSystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Network">
      <HintPath>{$mainBin}TaleWorlds.Network.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.PlatformService">
      <HintPath>{$mainBin}TaleWorlds.PlatformService.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.PlatformService.Epic">
      <HintPath>{$mainBin}TaleWorlds.PlatformService.Epic.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.PlatformService.Steam">
      <HintPath>{$mainBin}TaleWorlds.PlatformService.Steam.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.PlayerServices">
      <HintPath>{$mainBin}TaleWorlds.PlayerServices.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.PSAI">
      <HintPath>{$mainBin}TaleWorlds.PSAI.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.SaveSystem">
      <HintPath>{$mainBin}TaleWorlds.SaveSystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Starter.DotNetCore">
      <HintPath>{$mainBin}TaleWorlds.Starter.DotNetCore.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Starter.Library">
      <HintPath>{$mainBin}TaleWorlds.Starter.Library.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.TwoDimension">
      <HintPath>{$mainBin}TaleWorlds.TwoDimension.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.TwoDimension.Standalone">
      <HintPath>{$mainBin}TaleWorlds.TwoDimension.Standalone.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="{$this->entryPoint}.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
EOF;
         **/
        return file_put_contents($this->config->get()['folders']['src'] . "/{$this->modName}/{$this->modName}/.csproj", $file);
    }


    /**
     * @return string
     */
    public function getPath(): string
    {
        return $this->path;
    }

    /**
     * @param string $path
     */
    public function setPath(string $path): void
    {
        $this->path = $path;
    }

    /**
     * @return string
     */
    public function getProjectGUID(): string
    {
        return $this->projectGUID;
    }

    /**
     * @param string $projectGUID
     */
    public function setProjectGUID(string $projectGUID): void
    {
        $this->projectGUID = $projectGUID;
    }

    /**
     * @return string
     */
    public function getEntryPoint(): string
    {
        return $this->entryPoint;
    }

    /**
     * @param string $entryPoint
     */
    public function setEntryPoint(string $entryPoint): void
    {
        $this->entryPoint = $entryPoint;
    }
}